### ISSUE TITLE
install for brackets

### ISSUE THREAD

**Issue by ding-hub** [adambrgmn/eslint-plugin-extendscript#18]
Is there any way I can install this for brackets eslint? I tried a few unsuccessful attempts.  Any guidance will help.

Thanks

**Comment by adambrgmn** [comment]
Hm sorry but I have no experience of Brackets. I might be able to take a look tomorrow. 

Could you try to explain how one usually installs eslint-plugins with Brackets. And what goes wrong when you try to install eslint-plugin-extendscript?

**Comment by ding-hub** [comment]
I'm just trying to add it to the brackets modules directory but I guess that doesn't work. Maybe I should ask in the brackets github. What IDE are you using with this?

**Comment by ding-hub** [comment]
figured it out.
npm install this package inside brackets' "www/extensions/default/brackets-eslint"
put a file named ".eslintrc.js" in your .jsx's main directory with the following

```
module.exports = {
    "extends": "eslint:recommended", // or any other presets
    "plugins": ["extendscript"],
    "env": {
        "extendscript/base": true, // Basic suite available in all ExtendScript environments
        "extendscript/scriptui": true, // ScriptUI globals
        "extendscript/indesign": true, // InDesign globals
        "extendscript/photoshop": true, // Photoshop globals
        "extendscript/illustrator": true, // Illustrator globals
        "extendscript/after effects": true // after effects globals
    }
};
```

started working on after effects globals. do you know where you got all those definitions from?

**Comment by ding-hub** [comment]
found them here
[https://github.com/runegan/eslint-config-aftereffects/blob/master/index.js](url)

**Comment by ding-hub** [comment]
[globals.json.zip](https://github.com/adambrgmn/eslint-plugin-extendscript/files/1813982/globals.json.zip)
with after effects included

**Comment by adambrgmn** [comment]
Great that you figured it out! I'm mainly using Visual Studio Code. But I've seen it work both with Atom and with the CLI.

Do you mean that you want to add After Effects globals as well? That would be awesome! Feel free to open a pull request when you got it working.

I don't have After Effects installed at the moment, but I have a license for it, so I could help you out if you like to verify the globals in `eslint-config-aftereffects` are correct.

The Extendscript Scripting Dictionaries are usually found inside `/Library/Application Support/Adobe/Scripting Dictionaries CC` (on macOS at least, InDesign is found elsewhere).

[`scripts/get-extendscript-globals.js`](https://github.com/adambrgmn/eslint-plugin-extendscript/blob/master/scripts/get-extendscript-globals.js) takes care of parsing the dictionaries from XML into JSON. It might be worth adding After Effects there as well.

You can run the script with `npm run get-globals` (or `yarn get-globals`).
